In [1]:
import pandas as pd

In [113]:
df = pd.read_csv('delta_price_symbol_X.csv', index_col=None)

In [114]:
df_x = df.iloc[:, 1:]

In [115]:
df = pd.read_csv('delta_price_symbols_E_to_H.csv')
df_EH = df.iloc[:, 1:]

In [116]:
df = pd.read_csv('delta_price_symbols_A_to_D.csv')
df_AD = df.iloc[:, 1:]

In [126]:
df_all = df_x.merge(df_EH, on='Date').merge(df_AD, on='Date')

In [36]:
df_all.head()

,Date,delta_price_X,delta_price_E,delta_price_F,delta_price_G,delta_price_H,delta_price_A,delta_price_B,delta_price_C,delta_price_D
0,2018-06-04,0.163004,0.013106,0.008679,0.012875,0.009031,0.007782,0.004563,0.007087,0.004751
1,2018-06-05,-0.123008,0.008951,0.004531,0.005778,0.003098,0.001894,0.001235,-0.000292,0.000728
2,2018-06-06,0.044443,0.001774,0.004340,0.000402,0.005834,0.002690,0.007222,0.003319,0.008361
3,2018-06-07,0.008938,0.004971,0.000227,-0.003388,-0.008132,0.007832,0.002739,0.004544,-0.000108
4,2018-06-08,-0.145517,-0.012963,-0.005968,-0.002132,0.000057,-0.003958,-0.000108,0.001158,0.002956

In [129]:
min(df_all['Date'])

'2018-06-04'

In [130]:
max(df_all['Date'])

'2018-11-28'

In [48]:
import statsmodels.api as sm

In [42]:
y = df_all['delta_price_X']

In [50]:
X = df_all.iloc[:,2:]

In [51]:
results = sm.OLS(y, X).fit()

print(results.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:          delta_price_X   R-squared (uncentered):                   0.249
Model:                            OLS   Adj. R-squared (uncentered):              0.198
Method:                 Least Squares   F-statistic:                              4.849
Date:                Sat, 14 Aug 2021   Prob (F-statistic):                    3.53e-05
Time:                        14:26:49   Log-Likelihood:                          78.975
No. Observations:                 125   AIC:                                     -141.9
Df Residuals:                     117   BIC:                                     -119.3
Df Model:                           8
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
delta_price_E     2.4596      3.337      0.737      0.463      -4.150       9.069
delta_price_F    -2.0693      5.062     -0.409      0.683     -12.093       7.955
delta_price_G   -17.4807      4.190     -4.172      0.000     -25.778      -9.183
delta_price_H    13.7338      5.058      2.715      0.008       3.716      23.752
delta_price_A     8.2720      5.972      1.385      0.169      -3.555      20.099
delta_price_B    -0.1673      7.301     -0.023      0.982     -14.627      14.293
delta_price_C     9.2186      6.278      1.468      0.145      -3.214      21.652
delta_price_D    -9.0610      7.336     -1.235      0.219     -23.590       5.468
==============================================================================
Omnibus:                       29.332   Durbin-Watson:                   2.699
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               68.287
Skew:                           0.918   Prob(JB):                     1.49e-15
Kurtosis:                       6.121   Cond. No.                         22.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [95]:
infl_s = results.get_influence().summary_frame()
# df = infl['influence']

In [96]:
infl_s.describe()

,dfb_delta_price_E,dfb_delta_price_F,dfb_delta_price_G,dfb_delta_price_H,dfb_delta_price_A,dfb_delta_price_B,dfb_delta_price_C,dfb_delta_price_D,cooks_d,standard_resid,hat_diag,dffits_internal,student_resid,dffits
count,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,1.250000e+02,125.000000,125.000000,125.000000,125.000000,125.000000
mean,0.000790,-0.001345,-0.000660,0.000814,-0.000653,0.001453,0.000153,-0.000692,8.391885e-03,0.039208,0.064000,0.012101,0.044145,0.013408
std,0.096278,0.103540,0.082937,0.101458,0.089987,0.095121,0.074471,0.076818,2.463249e-02,1.001310,0.057997,0.259863,1.027938,0.267810
min,-0.609328,-0.782294,-0.474309,-0.304395,-0.494680,-0.286707,-0.188624,-0.277270,1.770704e-09,-2.099989,0.004277,-0.656293,-2.131552,-0.662109
25%,-0.021071,-0.030996,-0.028494,-0.038006,-0.029962,-0.026477,-0.028384,-0.019289,3.614588e-04,-0.574568,0.023412,-0.110111,-0.572916,-0.109833
50%,0.000027,0.002496,0.000054,-0.005263,-0.000034,-0.001535,-0.000026,0.000691,1.562496e-03,-0.034400,0.043370,-0.005450,-0.034253,-0.005427
75%,0.036551,0.034903,0.033853,0.022013,0.022530,0.024721,0.025864,0.033488,4.834609e-03,0.506213,0.083078,0.111803,0.504598,0.111574
max,0.497318,0.295847,0.237371,0.804961,0.498403,0.562983,0.380088,0.296587,2.420809e-01,4.751656,0.255743,1.391635,5.266691,1.542475

Delta Price G has lowest p-value

F and B are the least impactful with highet p-value

Normalize deltas for more volatile stocks

In [87]:
fts = list(df_all.columns[2:])

In [103]:
df_nrml = df_all
for x in fts:
    df_nrml[x] = pd.qcut(df_nrml[x], q=100, labels=False, duplicates='drop')

In [104]:
df_nrml.head()

,Date,delta_price_X,delta_price_E,delta_price_F,delta_price_G,delta_price_H,delta_price_A,delta_price_B,delta_price_C,delta_price_D
0,2018-06-04,0.163004,14,14,16,14,14,14,14,12
1,2018-06-05,-0.123008,12,12,12,10,8,10,7,8
2,2018-06-06,0.044443,8,12,7,12,10,16,10,14
3,2018-06-07,0.008938,10,8,3,3,14,12,12,7
4,2018-06-08,-0.145517,1,3,5,7,3,7,8,10

In [109]:
df_all.head()

,Date,delta_price_X,delta_price_E,delta_price_F,delta_price_G,delta_price_H,delta_price_A,delta_price_B,delta_price_C,delta_price_D
0,2018-06-04,0.163004,14,14,16,14,14,14,14,12
1,2018-06-05,-0.123008,12,12,12,10,8,10,7,8
2,2018-06-06,0.044443,8,12,7,12,10,16,10,14
3,2018-06-07,0.008938,10,8,3,3,14,12,12,7
4,2018-06-08,-0.145517,1,3,5,7,3,7,8,10

Remove Low performing variables - higher adj R squared

In [121]:
df_drop = df_all.drop(['delta_price_B','delta_price_F'], axis=1)

In [122]:
y = df_drop['delta_price_X']
X = df_drop.iloc[:,2:]

In [123]:
results = sm.OLS(y, X).fit()

print(results.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:          delta_price_X   R-squared (uncentered):                   0.246
Model:                            OLS   Adj. R-squared (uncentered):              0.208
Method:                 Least Squares   F-statistic:                              6.476
Date:                Sat, 14 Aug 2021   Prob (F-statistic):                    6.22e-06
Time:                        15:04:03   Log-Likelihood:                          78.739
No. Observations:                 125   AIC:                                     -145.5
Df Residuals:                     119   BIC:                                     -128.5
Df Model:                           6
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
delta_price_E     2.1134      2.620      0.807      0.422      -3.075       7.301
delta_price_G   -17.8148      4.123     -4.321      0.000     -25.978      -9.651
delta_price_H    12.7188      4.302      2.956      0.004       4.200      21.238
delta_price_A     6.7882      4.336      1.566      0.120      -1.797      15.374
delta_price_C    10.5194      5.926      1.775      0.078      -1.214      22.253
delta_price_D    -9.1987      6.459     -1.424      0.157     -21.988       3.591
==============================================================================
Omnibus:                       31.784   Durbin-Watson:                   2.707
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               78.296
Skew:                           0.975   Prob(JB):                     9.96e-18
Kurtosis:                       6.352   Cond. No.                         17.4
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.